alteryx_rewrite:
  target: dev
  outputs:
    dev:
      type: xxx
      account: xxx
      database: xxx
      schema: xxx
      warehouse: xxx
      role: xxx
      user: xxx
      password: xxx
      threads: 1
      client_session_keep_alive: False